---
- name:  "Ansible 2.11+ required"
  assert:
    that:
      - ansible_version is defined
      - ansible_version.full is version_compare('2.11', '>=')
    msg: "Required Ansible version is 4 with 2.11+ (core)"
  tags: always

- name: "Debian 10 or 11 required"
  assert:
    that:
      - ansible_distribution == "Debian"
      - ansible_distribution_major_version in [ "10", "11" ]
    msg: "Only Debian 10 adn 11 is supported, this is {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
  tags: always

- name: "get OS service facts"
  service_facts:
  tags: always

- name: "message-of-the-day setup"
  copy:
    src: motd
    dest: /etc/motd
  tags: motd

- name: "TLS certificates setup"
  import_tasks: perun_certs.yml
  tags: perun_certs

- name: "Operating System setup (firewall, yubikeys, monitoring)"
  import_tasks: os_setup.yml
  tags: os_setup

- name: "creation of users perun, peruneng, etc."
  import_tasks: perun_users.yml
  tags: perun_users

- name: "Postgres server setup"
  import_tasks: postgres.yml
  tags: postgresql

- name: "Postgres perun db setup"
  import_tasks: perun_postgres.yml
  tags: perun_postgres

- name: "Docker and Portainer setup"
  import_tasks: perun_docker.yml
  tags: perun_docker

- name: "SMTP setup for Dockerized environment"
  import_role:
    name: cesnet.sendmail_for_docker
  vars:
    sendmail_for_docker_hostname: "{{ perun_rpc_hostname }}"
    sendmail_for_docker_bridge_network_name: perun_net
    sendmail_for_docker_bridge_network_gateway: 192.168.0.1
    sendmail_for_docker_config: "{{ perun_sendmail_config }}"

- name: "OpenLDAP directory server installation"
  include_role:
    name: cesnet.openldap
    apply:
      tags:
        - perun_ldap
  when: perun_ldap_local
  vars:
    ldap_domain: "{{ perun_ldap_domain }}"
    ldap_top_organization: perun
    ldap_data_password: "{{ perun_ldap_data_password }}"
    ldap_config_password: "{{ perun_ldap_config_password }}"
    ldap_hold_package: yes
    ldap_certificate_file: "{{ perun_certificate_file }}"
    ldap_certificate_key_file: "{{ perun_certificate_key_file }}"
    ldap_certificate_chain_file: "{{ perun_certificate_chain_file }}"
    ldap_access_rules_set: no
    ldap_size_limit: "{{ perun_ldap_size_limit }}"
    ldap_master_replica: "{{ perun_ldap_master_replica }}"
    ldap_replication_password: "{{ perun_ldap_replication_password }}"
    ldap_users: "{{ perun_ldap_users }}"
  tags:
    - perun_ldap

- name: "prepare vars for perun_config"
  import_tasks: perun_config.yml
  tags:
    - perun_config
    - perun_rpc
    - perun_ldapc

- name: "OpenLDAP Perun specific settings"
  include_role:
    name: cesnet.perun_ldap_config
    apply:
      tags:
        - perun_ldap
        - perun_config
  tags:
    - perun_ldap
    - perun_config
  when: perun_ldap_local

- name: "setup of Docker data volumes for Perun containers"
  import_tasks: perun_volumes.yml
  tags: perun_volumes

- name: "site-specific tasks before perun config"
  when: perun_site_specific_tasks_before is defined
  include_tasks:
    file: "files/{{ perun_instance_hostname}}/{{ perun_site_specific_tasks_before }}"
    apply:
      tags:
        - site_specific
  tags:
    - site_specific

- name: "perun rpc setup"
  import_tasks: perun_rpc.yml
  tags:
    - perun_rpc
    - perun_config

- name: "perun engine setup"
  import_tasks: perun_engine.yml
  tags:
    - perun_engine
    - perun_config

- name: "perun ldapc setup"
  include_tasks: perun_ldapc.yml
    apply:
        tags:
          - perun_ldapc
          - perun_config
  tags:
    - perun_ldapc
    - perun_config
  when: perun_ldap_local

- name: "perun apache setup"
  import_tasks: perun_apache.yml
  tags:
    - perun_apache
    - perun_config

- name: "perun CLI setup"
  import_tasks: perun_cli.yml
  tags:
    - perun_cli
    - perun_config

- name: "site-specific tasks after perun config"
  when: perun_site_specific_tasks_after is defined
  include_tasks:
    file: "files/{{ perun_instance_hostname}}/{{ perun_site_specific_tasks_after }}"
    apply:
      tags:
        - site_specific
  tags:
    - site_specific