---
- name:  "Ansible 2.9+ required"
  assert:
    that:
      - ansible_version is defined
      - ansible_version.full is version_compare('2.9', '>=')
    msg: "Required Ansible version is 2.9+"

- name: "get OS service facts"
  service_facts:

- name: "message-of-the-day setup"
  copy:
    src: motd
    dest: /etc/motd
  tags: motd

- name: "TLS certificates setup"
  import_tasks: perun_certs.yml
  tags: perun_certs

- name: "Operating System setup (firewall, yubikeys, monitoring)"
  import_tasks: os_setup.yml
  tags: os_setup

- name: "SMTP setup"
  import_tasks: smtp_setup.yml
  tags: smtp_setup

- name: "Postgres server setup"
  import_tasks: postgres.yml
  tags: postgresql

- name: "Postgres perun db setup"
  import_tasks: perun_postgres.yml
  tags: perun_postgres

- name: "Docker and Portainer setup"
  import_tasks: perun_docker.yml
  tags: perun_docker

- name: "OpenLDAP directory server installation"
  import_tasks: perun_ldap_install.yml
  tags:
    - perun_ldap

- name: "OpenLDAP directory server config"
  import_tasks: perun_ldap_config.yml
  tags:
    - perun_ldap
    - perun_config

- name: "setup of Docker data volumes for Perun containers"
  import_tasks: perun_volumes.yml
  tags: perun_volumes

- name: "perun rpc setup"
  import_tasks: perun_rpc.yml
  tags:
    - perun_rpc
    - perun_config

- name: "perun engine setup"
  import_tasks: perun_engine.yml
  tags:
    - perun_engine
    - perun_config

- name: "perun ldapc setup"
  import_tasks: perun_ldapc.yml
  tags:
    - perun_ldapc
    - perun_config

- name: "perun apache setup"
  import_tasks: perun_apache.yml
  tags:
    - perun_apache
    - perun_config

- name: "perun CLI setup"
  import_tasks: perun_cli.yml
  tags:
    - perun_cli
    - perun_config

- name: "site-specific tasks"
  when: perun_site_specific_tasks is defined
  include_tasks:
    file: "files/{{ perun_instance_hostname}}/{{ perun_site_specific_tasks }}"
    apply:
      tags:
        - site_specific
  tags:
    - site_specific