---
- name:  "Ansible 2.9+ required"
  assert:
    that:
      - ansible_version is defined
      - ansible_version.full is version_compare('2.9', '>=')
    msg: "Required Ansible version is 2.9+"

- name: "TLS certificates setup"
  import_tasks: perun_certs.yml
  tags: perun_certs

- name: "Operating System setup (firewall, yubikeys, monitoring)"
  import_tasks: os_setup.yml
  tags: os_setup

- name: "Postgres server setup"
  import_tasks: postgres.yml
  tags: postgresql

- name: "Postgres perun db setup"
  import_tasks: perun_postgres.yml
  tags: perun_postgres

- name: "Docker server setup"
  import_tasks: perun_docker.yml
  tags: perun_docker

- name: "perun user setup"
  import_tasks: perun_user.yml
  tags: perun_user

- name: "Docker data volumes for Perun containers"
  import_tasks: perun_volumes.yml
  tags: perun_volumes

- name: "perun apache setup"
  import_tasks: perun_apache.yml
  tags:
    - perun_apache
    - perun_config

- name: "perun rpc setup"
  import_tasks: perun_rpc.yml
  tags:
    - perun_rpc
    - perun_config

- name: "perun containers setup"
  import_tasks: perun_containers.yml
  tags: perun_containers
