- name: "install OpenLDAP server"
  import_role:
    name: cesnet.openldap
  vars:
    ldap_domain: "{{ perun_ldap_domain }}"
    ldap_top_organization: perun
    ldap_data_password: "{{ perun_ldap_data_password }}"
    ldap_config_password: "{{ perun_ldap_config_password }}"
    ldap_hold_package:  yes
    ldap_certificate_file: "{{ perun_certificate_file }}"
    ldap_certificate_key_file: "{{ perun_certificate_key_file }}"
    ldap_certificate_chain_file: "{{ perun_certificate_chain_file }}"
    ldap_access_rules_start: "{{ perun_ldap_access_rules_start }}"
    ldap_access_rules_additional: "{{ perun_ldap_access_rules_additional }}"
    ldap_access_rules_end: "{{ perun_ldap_access_rules_end }}"
    ldap_size_limit: "{{ perun_ldap_size_limit }}"
    ldap_master_replica: "{{ perun_ldap_master_replica }}"
    ldap_replication_password: "{{ perun_ldap_replication_password }}"
    ldap_users: "{{ perun_ldap_users }}"
