- name: "set working environment"
  import_role:
    name: cesnet.work_env

- import_role:
    name: cesnet.ntp

- name: "set up monitoring by MetaCentrum's Nagios"
  include_role:
    name: cesnet.metacentrum_monitoring
    apply:
      tags:
        - metacentrum_monitoring
  when: perun_metacentrum_monitoring
  vars:
    monitoring_check_mk_config: "{{ perun_monitoring_check_mk_config }}"
  tags:
    - metacentrum_monitoring

- name: "set up unattended upgrades"
  import_role:
    name: "cesnet.unattended_upgrades"
  vars:
    unattended_upgrades_origin_patterns: "{{ perun_unattended_upgrades_origin_patterns }}"
    unattended_upgrades_blacklist: "{{ perun_unattended_upgrades_blacklist }}"
    unattended_upgrades_automatic_reboot: "{{ perun_unattended_upgrades_automatic_reboot }}"
    root_email_address: "{{ perun_root_email_address }}"
    unattended_upgrades_mta_package: "msmtp-mta"
    unattended_upgrades_mail_package: "bsd-mailx"

- name: "set up Yubikeys"
  import_role:
    name: cesnet.yubikeys
  vars:
    other_sudo_user: "perun"
    yubikey_users: "{{ perun_yubikey_users }}"
    yubikey_id: "{{ perun_yubikey_id }}"
    yubikey_key: "{{ perun_yubikey_key }}"
    yubikey_lognames: "{{ perun_yubikey_lognames }}"
    sudo_root_lognames: "{{ perun_sudo_root_lognames }}"
    sudo_other_lognames: "{{ perun_sudo_perun_lognames }}"

- name: "set root ssh keys"
  authorized_key:
    user: root
    key: "{{ perun_yubikey_users[item].rootkey }}"
    state: present
  loop: "{{ perun_root_users }}"

