- name: "set working environment"
  import_role:
    name: martin_kuba.work_env

- name: "set firewall"
  import_role:
    name: cesnet.firewall
  vars:
    firewall_rules_type: iptables
    firewall_open_tcp_ports: "{{ perun_firewall_open_tcp_ports }}"
    firewall_docker_rules: "{{ perun_firewall_docker_rules }}"

- name: "set up monitoring by MetaCentrum's Nagios"
  import_role:
    name: cesnet.metacentrum_monitoring

- name: "set up unattended upgrades"
  import_role:
    name: "cesnet.unattended_upgrades"
  vars:
    unattended_upgrades_origin_patterns: "{{ perun_unattended_upgrades_origin_patterns }}"
    unattended_upgrades_blacklist: "{{ perun_unattended_upgrades_blacklist }}"
    root_email_address: "{{ perun_root_email_address }}"

- name: "set up Yubikeys"
  import_role:
    name: cesnet.yubikeys
  vars:
    other_sudo_user: "perun"
    yubikey_users: "{{ perun_yubikey_users }}"
    yubikey_id: "{{ perun_yubikey_id }}"
    yubikey_key: "{{ perun_yubikey_key }}"
    yubikey_lognames: "{{ perun_yubikey_lognames }}"
    sudo_root_lognames: "{{ perun_sudo_root_lognames }}"
    sudo_other_lognames: "{{ perun_sudo_perun_lognames }}"

- name: "set root ssh keys"
  authorized_key:
    user: root
    key: "{{ perun_yubikey_users[item].rootkey }}"
    state: present
  loop: "{{ perun_root_users }}"

- name: "create perun groups"
  group:
    name: "{{ item.name }}"
    system: yes
    gid: "{{ item.gid }}"
  loop:
    - { name: perun, gid: 960 }
    - { name: perunrpc, gid: 961 }
    - { name: peruneng, gid: 962 }
    - { name: perunldc, gid: 963 }
    - { name: _shibd, gid: 964 }

- name: "create perun users"
  user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    group: "{{ item.name }}"
    comment: "{{ item.comment }}"
    shell: "{{ item.shell }}"
    system: yes
    create_home: "{{ item.home }}"
  loop:
    - { name: perun,    uid: 960, comment: "Perun", home: yes, shell: /bin/bash }
    - { name: perunrpc, uid: 961, comment: "Perun RPC", home: no, shell: /bin/bash }
    - { name: peruneng, uid: 962, comment: "Perun Engine", home: no, shell: /bin/bash }
    - { name: perunldc, uid: 963, comment: "Perun LDAP Connector", home: no, shell: /bin/bash }
    - { name: _shibd,   uid: 964, comment: "Shibboleth daemon", home: no, shell: /usr/sbin/nologin }

- name: "create /home/perun/Perun_README.txt"
  template:
    src: Perun_README.txt.j2
    dest: /home/perun/Perun_README.txt
    owner: perun
    group: perun
    mode: '0544'