- name: "install syslog-ng"
  apt:
    name: syslog-ng
    state: present

- name: "create vinovago.conf for syslog-ng"
  when: perun_syslog_vinovago_enabled
  template:
    src: vinovago.conf.j2
    dest: /etc/syslog-ng/conf.d/vinovago.conf
  notify: "reload syslog-ng"

- name: "remove vinovago.conf"
  when: not perun_syslog_vinovago_enabled
  file:
    path: /etc/syslog-ng/conf.d/vinovago.conf
    state: absent
  notify: "reload syslog-ng"

- name: "set FQDN in syslog"
  lineinfile:
    path: /etc/syslog-ng/syslog-ng.conf
    regexp: '^options { (.*) use_fqdn\((\w)+\);$'
    line: 'options { \1 use_fqdn(yes);'
    backrefs: yes
  notify: "reload syslog-ng"

- name: "flush handlers"
  meta: flush_handlers
