- name: "prereqs"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - software-properties-common
    state: present

- name: "add Docker repository key"
  apt_key:
    id: 0EBFCD88
    keyring: /etc/apt/trusted.gpg.d/docker.gpg
    url: "https://download.docker.com/linux/debian/gpg"
    state: present

- name: "add Docker repository"
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    filename: 'docker'
    state: present
  register: dockerrepo

- name: "update from new repo"
  when: dockerrepo.changed
  apt:
    update_cache: yes

- name: "install Docker"
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - python-docker
      - python3-docker
      - pass
    state: present

- name: "set MTU to 1442 to enable Docker to run on OpenStack"
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
       "mtu": 1442
      }
  register: mtu

- name: "restart Docker after changing MTU"
  when: mtu.changed
  service:
    name: docker
    state: restarted

# install Portainer web app for managing containers
- name: "create volume for portainer"
  docker_volume:
    name: portainer_data

- name: "create password file"
  copy:
    dest: "{{ perun_certs_dir }}/portainer_admin_password.txt"
    content: "{{ perun_portainer_admin_password }}"
    owner: root
    group: perun
    mode: '0640'

- name: "install portainer container"
  docker_container:
    name: portainer
    image: "portainer/portainer-ce:latest"
    pull:  yes
    restart_policy: always
    command: "-H unix:///var/run/docker.sock --ssl --sslcert {{ perun_certificate_fullchain_file }} --sslkey {{ perun_certificate_key_file }} --admin-password-file {{ perun_certs_dir }}/portainer_admin_password.txt"
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - "{{ perun_certs_dir }}:{{ perun_certs_dir }}:ro"
  register: portainer_container

- name: "login into gitlab docker registry"
  docker_login:
    registry_url: "registry.gitlab.ics.muni.cz:443"
    username: "gitlab-read-only-deploy-token-perun-docker"
    password: "K3tG1Np-yLVWB51jj3bB"

- name: "create a local Docker network for Perun"
  docker_network:
    name: perun_net
    driver_options:
      com.docker.network.driver.mtu: 1442
    ipam_config:
      - subnet: 192.168.0.0/24
        gateway: 192.168.0.1
