# add host names to CORS domains if not present

- name: "add {{ 'https://' + perun_ngui_admin_hostname }} to CORS domains"
  when: perun_ngui_enabled and ('https://' + perun_ngui_admin_hostname) not in perun_rpc_cors_domains
  set_fact:
    perun_rpc_cors_domains: "{{ perun_rpc_cors_domains + [ 'https://' + perun_ngui_admin_hostname ] }}"

- name: "add {{ 'https://' + perun_ngui_profile_hostname }} to CORS domains"
  when: perun_ngui_profile_enabled and ('https://' + perun_ngui_profile_hostname) not in perun_rpc_cors_domains
  set_fact:
    perun_rpc_cors_domains: "{{ perun_rpc_cors_domains + [ 'https://' + perun_ngui_profile_hostname ] }}"

- name: "add {{ 'https://' + perun_ngui_pwdreset_hostname }} to CORS domains"
  when: perun_ngui_pwdreset_enabled and ('https://' + perun_ngui_pwdreset_hostname) not in perun_rpc_cors_domains
  set_fact:
    perun_rpc_cors_domains: "{{ perun_rpc_cors_domains + [ 'https://' + perun_ngui_pwdreset_hostname ] }}"

- name: "add {{ 'https://' + perun_ngui_publications_hostname }} to CORS domains"
  when: perun_ngui_publications_enabled and ('https://' + perun_ngui_publications_hostname) not in perun_rpc_cors_domains
  set_fact:
    perun_rpc_cors_domains: "{{ perun_rpc_cors_domains + [ 'https://' + perun_ngui_publications_hostname ] }}"

- name: "add {{ 'https://' + perun_ngui_consolidator_hostname }} to CORS domains"
  when: perun_ngui_consolidator_enabled and ('https://' + perun_ngui_consolidator_hostname) not in perun_rpc_cors_domains
  set_fact:
    perun_rpc_cors_domains: "{{ perun_rpc_cors_domains + [ 'https://' + perun_ngui_consolidator_hostname ] }}"

- name: "add {{ 'https://' + perun_ngui_linker_hostname }} to CORS domains"
  when: perun_ngui_linker_enabled and ('https://' + perun_ngui_linker_hostname) not in perun_rpc_cors_domains
  set_fact:
    perun_rpc_cors_domains: "{{ perun_rpc_cors_domains + [ 'https://' + perun_ngui_linker_hostname ] }}"

- name: "CORS domains are:"
  debug:
    var: perun_rpc_cors_domains

