- name: "compute baseDN"
  set_fact:
    perun_ldap_basedn: '{{ "dc=" + perun_ldap_domain.split(".") | join(",dc=") }}'

- name: "compute admin DN"
  set_fact:
    perun_ldap_data_admin_dn: '{{ "cn=admin," + perun_ldap_basedn }}'

- name: "create perun-ldapc.properties"
  template:
    src: perun-ldapc.properties.j2
    dest: /etc/perun/ldapc/perun-ldapc.properties
    owner: perunldc
    group: perunldc
    mode: 0440
  notify: "restart perun_ldapc"

# files jdbc.properties, perun.properties and perun-roles.yml are nneded because LDAPc includes Perun core
- name: "create jdbc.properties (contains db password)"
  template:
    src: jdbc.properties.j2
    dest: /etc/perun/ldapc/jdbc.properties
    owner: perunldc
    group: perunldc
    mode: 0440
  notify: "restart perun_ldapc"

- name: "create perun.properties (contains several variables)"
  template:
    src: perun.properties.j2
    dest: /etc/perun/ldapc/perun.properties
    owner: perunldc
    group: perunldc
    mode: 0440
  notify: "restart perun_ldapc"

- name: "create perun-roles.yml"
  template:
    src: perun-roles.yml.j2
    dest: /etc/perun/ldapc/perun-roles.yml
    owner: perunldc
    group: perunldc
    mode: 0440
  notify: "restart perun_ldapc"

- name: "create logback-ldapc.xml"
  template:
    src: logback-ldapc.xml.j2
    dest: /etc/perun/ldapc/logback-ldapc.xml
    owner: perunldc
    group: perunldc
    mode: 0440

- name: "create perun-ldapc"
  template:
    src: perun-ldapc.j2
    dest: /etc/perun/ldapc/perun-ldapc
    owner: perunldc
    group: perunldc
    mode: 0440

- name: "create perun-rpc-lib.properties"
  template:
    src: perun-rpc-lib.properties.j2
    dest: /etc/perun/ldapc/perun-rpc-lib.properties
    owner: perunldc
    group: perunldc
    mode: 0440

- name: "create perun-ldapc-attributes.xml"
  copy:
    src: "{{ lookup('first_found', findme) }}"
    dest: /etc/perun/ldapc/perun-ldapc-attributes.xml
    owner: perunldc
    group: perunldc
    mode: 0440
  vars:
    findme:
      - "{{ perun_instance_hostname }}/perun-ldapc-attributes.xml"
      - "perun-ldapc-attributes.xml"
  notify: "restart perun_ldapc"

- name: "create perun-ldapc-last-state"
  copy:
    force: no
    dest: /home/perunldc/perun-ldapc-last-state
    content: "0"
    owner: perunldc
    group: perunldc

- name: "create jdbc.properties (contains db password)"
  template:
    src: jdbc.properties.j2
    dest: /etc/perun/ldapc/jdbc.properties
    owner: perunldc
    group: perunldc
    mode: 0440
  notify: "restart perun_ldapc"

- name: "create Perun LDAPc container"
  docker_container:
    name: perun_ldapc
    image: "registry.gitlab.ics.muni.cz:443/perun/perun_docker/perun_ldapc:{{ perun_ldapc_container_version }}"
    pull: yes
    restart_policy: unless-stopped
    mounts:
      - { type: volume, source: perun_logs, target: /var/log/perun }
      - { type: volume, source: perunldc_home, target: /home/perun }
      - { type: volume, source: perunldc_etc,  target: /etc/perun }
    networks_cli_compatible: yes
    networks:
      - name: perun_net
  register: perun_ldapc_container

- name: "put container IP into /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: 'perun_ldapc'
    line: "{{ perun_ldapc_container.container.NetworkSettings.Networks.perun_net.IPAddress }} perun_ldapc"