- name: "create perun-engine.properties"
  template:
    src: perun-engine.properties.j2
    dest: /etc/perun/engine/perun-engine.properties
    owner: peruneng
    group: peruneng
    mode: 0440
  notify: "restart perun_engine"

- name: "create logback-engine.xml"
  template:
    src: logback-engine.xml.j2
    dest: /etc/perun/engine/logback-engine.xml
    owner: peruneng
    group: peruneng
    mode: 0440

- name: "create perun-engine (contains password)"
  template:
    src: perun-engine.j2
    dest: /etc/perun/engine/perun-engine
    owner: peruneng
    group: peruneng
    mode: 0440
  notify: "restart perun_engine"

- name: "create directory .ssh"
  file:
    state: directory
    path: /home/peruneng/.ssh
    owner: peruneng
    group: peruneng
    mode: 0700

- name: "create ssh private key {{ perun_engine_ssh_privkey_file }} for accessing slaves"
  copy:
    src: "{{ lookup('first_found', findme) }}"
    dest: "/home/peruneng/.ssh/{{ perun_engine_ssh_privkey_file }}"
    owner: peruneng
    group: peruneng
    mode: 0600
  vars:
    findme:
      - "{{ perun_instance_hostname }}/{{ perun_engine_ssh_privkey_file }}"
      - "{{ perun_engine_ssh_privkey_file }}"

- name: "create ssh public key {{ perun_engine_ssh_pubkey_file }} for accessing slaves"
  copy:
    src: "{{ lookup('first_found', findme) }}"
    dest: "/home/peruneng/.ssh/{{ perun_engine_ssh_pubkey_file }}"
    owner: peruneng
    group: peruneng
    mode: 0644
  vars:
    findme:
      - "{{ perun_instance_hostname }}/{{ perun_engine_ssh_pubkey_file }}"
      - "{{ perun_engine_ssh_pubkey_file }}"

- name: "detect local directory"
  local_action:
    module: stat
    path: "files/{{ inventory_hostname }}/services"
  register: hs

- name: "recursive copy to /etc/perun/engine/services"
  when: hs.stat.exists
  copy:
    src: "{{ hs.stat.path }}"
    dest: /etc/perun/engine/
    owner: peruneng
    group: peruneng
    directory_mode: '0550'
    mode: '0440'

- name: "create Perun engine container"
  docker_container:
    name: perun_engine
    image: "registry.gitlab.ics.muni.cz:443/perun/perun_docker/perun_engine:{{ perun_engine_container_version }}"
    pull: yes
    restart_policy: unless-stopped
    mounts:
      - { type: volume, source: perun_logs, target: /var/log/perun }
      - { type: volume, source: peruneng_home, target: /home/perun }
      - { type: volume, source: peruneng_etc,  target: /etc/perun }
    networks_cli_compatible: yes
    networks:
      - name: perun_net
  register: perun_engine_container

- name: "put container IP into /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: 'perun_engine'
    line: "{{ perun_engine_container.container.NetworkSettings.Networks.perun_net.IPAddress }} perun_engine"
