- name: "create jdbc.properties"
  template:
    src: jdbc.properties.j2
    dest: /etc/perun/perunrpc/jdbc.properties
    owner: perunrpc
    group: perunrpc
    mode: 0440
  notify: "restart perun_rpc"

- name: "create perun-roles.yml"
  template:
    src: perun-roles.yml.j2
    dest: /etc/perun/perunrpc/perun-roles.yml
    owner: perunrpc
    group: perunrpc
    mode: 0440

- name: "create perun-web-gui.properties (contains several variables)"
  template:
    src: perun-web-gui.properties.j2
    dest: /etc/perun/perunrpc/perun-web-gui.properties
    owner: perunrpc
    group: perunrpc
    mode: 0440
  notify: "restart perun_rpc"

- name: "create perun.properties (contains several variables)"
  template:
    src: perun.properties.j2
    dest: /etc/perun/perunrpc/perun.properties
    owner: perunrpc
    group: perunrpc
    mode: 0440
  notify: "restart perun_rpc"

- name: "create logback.xml"
  template:
    src: logback.xml.j2
    dest: /etc/perun/perunrpc/logback.xml
    owner: perunrpc
    group: perunrpc
    mode: 0440

- name: "create perun-cabinet.properties"
  template:
    src: perun-cabinet.properties.j2
    dest: /etc/perun/perunrpc/perun-cabinet.properties
    owner: perunrpc
    group: perunrpc
    mode: 0440

- name: "create perun-dispatcher.properties"
  template:
    src: perun-dispatcher.properties.j2
    dest: /etc/perun/perunrpc/perun-dispatcher.properties
    owner: perunrpc
    group: perunrpc
    mode: 0440

- name: "create perun-notification.properties"
  template:
    src: perun-notification.properties.j2
    dest: /etc/perun/perunrpc/perun-notification.properties
    owner: perunrpc
    group: perunrpc
    mode: 0440

- name: "create perun-extSources.xml"
  copy:
    src: "{{ lookup('first_found', findme) }}"
    dest: "/etc/perun/perunrpc/perun-extSources.xml"
    owner: perunrpc
    group: perunrpc
    mode: 0440
  vars:
    findme:
      - "{{ inventory_hostname }}/perun-extSources.xml"
      - "perun-extSources.xml"
  notify: "restart perun_rpc"


