- name: "prereqs"
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gpg
      - software-properties-common
    state: present

- name: "create /etc/apt/keyrings"
  file:
    state: directory
    path: /etc/apt/keyrings
    owner: root
    group: root
    mode: '0755'

- name: "add Docker repository key"
  get_url:
    url: "https://download.docker.com/linux/debian/gpg"
    dest: /etc/apt/keyrings/docker.asc
    force: false

- name: "clean old line without signed-by"
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: absent

- name: "add Docker repository"
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    filename: 'docker'
    state: present

- set_fact:
    docker_packages:
      - docker-ce
      - docker-ce-cli
      - docker-ce-rootless-extras
      - containerd.io

- name: "install docker packages"
  apt:
    state: present
    name: "{{ item }}"
  loop: "{{ docker_packages }}"

- name: "hold docker packages from upgrading"
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  loop: "{{ docker_packages }}"

- name: "install python-docker"
  apt:
    name:
      - python3-docker
      - pass
    state: present

- name: "change /etc/docker/daemon.json"
  template:
    src: templates/docker/daemon.json.j2
    dest: /etc/docker/daemon.json
  register: daemon_json

- name: "restart Docker after changing daemon.json"
  when: daemon_json.changed
  service:
    name: docker
    state: restarted

# install Portainer web app for managing containers
- name: "create volume for portainer"
  docker_volume:
    name: portainer_data

- name: "create password file"
  copy:
    dest: "{{ perun_certs_dir }}/portainer_admin_password.txt"
    content: "{{ perun_portainer_admin_password }}"
    owner: root
    group: perun
    mode: '0640'

- name: "list normal portainer volumes"
  set_fact:
    portainer_mounts:
      - { type: bind, source: /var/run/docker.sock, target: /var/run/docker.sock }
      - { type: volume, source: portainer_data, target: /data }
      - { type: bind, source: "{{ perun_certs_dir }}", target: "{{ perun_certs_dir }}", read_only: yes }

- name: "add certbot dirs to portainer volumes"
  when: perun_use_certbot_certificates
  set_fact:
    portainer_mounts: "{{ portainer_mounts + perun_certbot_mounts }}"

- name: "install portainer container"
  docker_container:
    name: portainer
    image: "portainer/portainer-ce:latest"
    pull:  yes
    restart_policy: always
    command: "-H unix:///var/run/docker.sock --http-disabled --sslcert {{ perun_certificate_fullchain_file }} --sslkey {{ perun_certificate_key_file }} --admin-password-file {{ perun_certs_dir }}/portainer_admin_password.txt"
    ports:
      - 9000:9443
    default_host_ip: ''
    mounts: "{{ portainer_mounts }}"
    container_default_behavior: no_defaults
  register: portainer_container

- name: "login into gitlab docker registry"
  docker_login:
    registry_url: "registry.gitlab.ics.muni.cz:443"
# perun_docker only:
#    username: "gitlab-read-only-deploy-token-perun-docker"
#    password: "K3tG1Np-yLVWB51jj3bB"
# whole perun:
    username: "gitlab-read-only-deploy-token-perun-all"
    password: "BgdJHJ_gsmyqp3se5WRx"

- name: "create a local Docker network for Perun"
  docker_network:
    name: perun_net
    driver_options:
      com.docker.network.driver.mtu: "{{ ansible_default_ipv4.mtu }}"
    ipam_config:
      - subnet: 192.168.0.0/24
        gateway: 192.168.0.1

- name: "put portainer IP into /etc/hosts"
  lineinfile:
    dest: /etc/hosts
    regexp: 'portainer'
    line: "{{ portainer_container.container.NetworkSettings.IPAddress }} portainer"
