- name: "add user perun to group docker"
  user:
    name: perun
    groups: docker
    append: yes

- name: "create docker volumes for data"
  include_tasks:
    file: volume_dir.yml
    apply:
      tags:
        - perun_volumes
  loop:
    - { name: 'perun_logs', link: "/var/log/perun", owner: perun, group: perun, mode: '1777' }
    - { name: 'perunrpc_home', link: "/home/perunrpc", owner: perunrpc, group: perunrpc, mode: '770' }
    - { name: 'peruneng_home', link: "/home/peruneng", owner: peruneng, group: peruneng, mode: '770' }
    - { name: 'perunldc_home', link: "/home/perunldc", owner: perunldc, group: perunldc, mode: '770' }
    - { name: 'perunalg_home', link: "/home/perunalg", owner: perunalg, group: perunalg, mode: '770' }
    - { name: 'perunrpc_etc',  link: "/etc/perun/rpc", owner: root, group: perunrpc, mode: '550' }
    - { name: 'peruneng_etc',  link: "/etc/perun/engine", owner: root, group: peruneng, mode: '550' }
    - { name: 'perunldc_etc',  link: "/etc/perun/ldapc", owner: root, group: perunldc, mode: '550' }
    - { name: 'perunalg_etc',  link: "/etc/perun/auditlogger", owner: root, group: perunalg, mode: '550' }
  loop_control:
    loop_var: volume
    label: "{{ volume.name }}"

- name: "create volume for apache logs"
  docker_volume:
    name: apache_logs
  register: volume_apache_logs

- name: "create link /var/log/apache2 to volume apache_logs"
  file:
    state: link
    src: "{{ volume_apache_logs.volume.Mountpoint }}"
    path: /var/log/apache2
    force: yes

- name: "create directory for shibboleth logs"
  file:
    path: /var/log/apache2/shibboleth
    state: directory
    owner: _shibd
    group: _shibd
    mode: '0755'

- name: "create link /var/log/shibboleth"
  file:
    state: link
    src: /var/log/apache2/shibboleth
    path: /var/log/shibboleth
    force: yes

- name: "set permissions for /var/log/apache2 to allow _shibd go through"
  file:
    path: /var/log/apache2
    mode: '0755'
    owner: root
    group: adm
