- name: "add user perun to group docker"
  user:
    name: perun
    groups: docker
    append: yes

- name: "create docker volumes for data"
  include_tasks:
    file: volume_dir.yml
    apply:
      tags:
        - perun_volumes
  loop:
    - { name: 'perun_logs', link: "/var/log/perun", owner: perun, mode: '1777' }
    - { name: 'perunrpc_home', link: "/home/perunrpc", owner: perunrpc, mode: '770' }
    - { name: 'peruneng_home', link: "/home/peruneng", owner: peruneng, mode: '770' }
    - { name: 'perunldc_home', link: "/home/perunldc", owner: perunldc, mode: '770' }
    - { name: 'perunrpc_etc',  link: "/etc/perun/perunrpc", owner: perunrpc, mode: '770' }
    - { name: 'peruneng_etc',  link: "/etc/perun/peruneng", owner: peruneng, mode: '770' }
    - { name: 'perunldc_etc',  link: "/etc/perun/perunldc", owner: perunldc, mode: '770' }
  loop_control:
    loop_var: volume
    label: "{{ volume.name }}"

- name: "create volume for apache logs"
  docker_volume:
    name: apache_logs
  register: volume_apache_logs

- name: "create link /var/log/apache2 to volume apache_logs"
  file:
    state: link
    src: "{{ volume_apache_logs.volume.Mountpoint }}"
    path: /var/log/apache2
    force: yes
