- name: "add unaccent extension"
  become: yes
  become_user: postgres
  postgresql_ext:
    db: "perun"
    name: unaccent

- name: "detect whether table users exists"
  become: yes
  become_user: postgres
  postgresql_query:
    session_role: perun
    db: perun
    query: "SELECT EXISTS ( SELECT 1 FROM information_schema.tables WHERE table_schema = 'perun' AND table_name = 'users' )"
  register: table_users

- name: "download SQL script for creating tables"
  get_url:
    url: "https://raw.githubusercontent.com/CESNET/perun/{{ perun_rpc_git_version }}/perun-db/postgres.sql"
    dest: /tmp/postgres.sql
  when: not table_users.query_result[0].exists

- name: "create perun tables"
  become: yes
  become_user: postgres
  postgresql_query:
    session_role: perun
    db: perun
    path_to_script: /tmp/postgres.sql
  when: not table_users.query_result[0].exists

