- name: "create perun-ldapc.properties"
  template:
    src: perun-ldapc.properties.j2
    dest: /etc/perun/ldapc/perun-ldapc.properties
    owner: root
    group: perunldc
    mode: 0440
  notify: "restart perun_ldapc"

# files jdbc.properties, perun.properties, perun-roles.yml and login-namespaces-rules-config.yml are needed because LDAPc includes Perun core
- name: "create jdbc.properties for LDAPc)"
  template:
    src: jdbc.properties.j2
    dest: /etc/perun/ldapc/jdbc.properties
    owner: root
    group: perunldc
    mode: 0440
  notify: "restart perun_ldapc"

- name: "create perun.properties for LDAPc"
  template:
    src: perun.properties.j2
    dest: /etc/perun/ldapc/perun.properties
    owner: root
    group: perunldc
    mode: 0440
  notify: "restart perun_ldapc"

- name: "create perun-apps-config.yml for LDAPc"
  template:
    src: perun-apps-config.yml.j2
    dest: /etc/perun/ldapc/perun-apps-config.yml
    owner: root
    group: perunldc
    mode: '0440'
  notify: "restart perun_ldapc"

- name: "create perun-roles.yml for LDAPc"
  template:
    src: perun-roles.yml.j2
    dest: /etc/perun/ldapc/perun-roles.yml
    owner: root
    group: perunldc
    mode: 0440
  notify: "restart perun_ldapc"

- name: "create login-namespaces-rules-config.yml"
  copy:
    src: "{{ lookup('first_found', findme) }}"
    dest: /etc/perun/ldapc/login-namespaces-rules-config.yml
    owner: root
    group: perunldc
    mode: 0440
  vars:
    findme:
      - "{{ perun_instance_hostname }}/login-namespaces-rules-config.yml"
      - "login-namespaces-rules-config.yml"
  notify: "restart perun_ldapc"

- name: "create logback-ldapc.xml"
  template:
    src: logback-ldapc.xml.j2
    dest: /etc/perun/ldapc/logback-ldapc.xml
    owner: root
    group: perunldc
    mode: 0440
  notify: "restart perun_ldapc"

- name: "create perun-ldapc"
  template:
    src: perun-ldapc.j2
    dest: /etc/perun/ldapc/perun-ldapc
    owner: root
    group: perunldc
    mode: 0440
  notify: "restart perun_ldapc"

- name: "create perun-ldapc-attributes.xml"
  copy:
    src: "{{ lookup('first_found', findme) }}"
    dest: /etc/perun/ldapc/perun-ldapc-attributes.xml
    owner: root
    group: perunldc
    mode: 0440
  vars:
    findme:
      - "{{ perun_instance_hostname }}/perun-ldapc-attributes.xml"
      - "perun-ldapc-attributes.xml"
  notify: "restart perun_ldapc"

- name: "create perun-ldapc-last-state"
  copy:
    force: no
    dest: /home/perunldc/perun-ldapc-last-state
    content: "0"
    owner: perunldc
    group: perunldc

- name: "get perun_net info"
  docker_network_info:
    name: perun_net
  register: perun_net_info

- name: "{{ 'create' if perun_ldapc_enabled else 'remove' }} Perun LDAPc container"
  docker_container:
    name: perun_ldapc
    hostname: perun-ldapc
    image: "registry.gitlab.ics.muni.cz:443/perun/perun_docker/perun_ldapc:{{ perun_ldapc_container_version }}"
    pull: yes
    restart_policy: unless-stopped
    mounts:
      - { type: volume, source: perunldc_home, target: /home/perun }
      - { type: volume, source: perunldc_etc,  target: /etc/perun }
      # bind syslog and journal from container to host, see https://www.projectatomic.io/blog/2016/10/playing-with-docker-logging/
      - { type: bind, source: /dev/log, target: /dev/log }
      - { type: bind, source: /var/run/systemd/journal/socket, target: /var/run/systemd/journal/socket }
    networks_cli_compatible: yes
    networks:
      - name: perun_net
    network_mode: perun_net
    etc_hosts: "{{ perun_containers_etc_hosts | combine( { 'perun-host': perun_net_info.network.IPAM.Config[0].Gateway }) }}"
    container_default_behavior: no_defaults
    state: "{{ 'started' if perun_ldapc_enabled else 'absent' }}"
  register: perun_ldapc_container

- name: "remove old hostname"
  lineinfile:
    dest: /etc/hosts
    regexp: 'perun_ldapc'
    state: absent

- name: "put container IP into /etc/hosts"
  when: perun_ldapc_enabled
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ perun_ldapc_container.container.Config.Hostname }}"
    line: "{{ perun_ldapc_container.container.NetworkSettings.Networks.perun_net.IPAddress }} {{ perun_ldapc_container.container.Config.Hostname }}"
