- name: "install PostgreSQL"
  import_role:
    name: cesnet.postgresql
  vars:
    postgresql_version: "{{ perun_postgresql_version }}"
    postgresql_certificate_file: "{{ perun_certificate_file }}"
    postgresql_certificate_key_file: "{{ perun_certificate_key_file }}"
    postgresql_certificate_chain_file: "{{ perun_certificate_chain_file }}"
    postgresql_db_user_password: "{{ perun_postgresql_db_user_password }}"
    postgresql_settings: "{{ perun_postgresql_settings }}"
    postgresql_daily_backup: yes
    postgresql_hold_upgrades: yes
    postgresql_db_user: "perun"
    postgresql_db_name: "perun"

- name: "install pipe viewer"
  apt:
    name: pv
    state: present

