# os_setup.yml called cesnet.unattended_upgrades that installed sendmail already

- name: "make sendmail to receive SMTP from docker containers"
  lineinfile:
    path: /etc/mail/sendmail.mc
    regexp: 'DAEMON_OPTIONS\(\`Family=inet,  Name=MTA-v4, Port=smtp,'
    line:   "DAEMON_OPTIONS(`Family=inet,  Name=MTA-v4, Port=smtp, Addr=0.0.0.0')dnl"
  register: smtp_ip_address

- name: "add lines to sendmail.mc (usually to set SMTP relay)"
  blockinfile:
    dest: /etc/mail/sendmail.mc
    marker: 'dnl # {mark} ANSIBLE MANAGED BLOCK'
    block: "{{ perun_sendmail_config }}"
  register: smtp_relay

- name: "allow relaying from docker subnet"
  blockinfile:
    dest: /etc/mail/access
    marker: '# {mark} ANSIBLE MANAGED BLOCK'
    block: |
      Connect:192.168 RELAY
  register: smtp_subnet

- name: "rebuild sendmail files"
  when: smtp_ip_address.changed or smtp_relay.changed or smtp_subnet.changed
  command:
    chdir: /etc/mail
    cmd: "make"
  register: sendmail_reloaded

- name: "set hostname"
  hostname:
    name: "{{ perun_rpc_hostname }}"

- name: "set /etc/hostname"
  copy:
    dest: /etc/hostname
    content: "{{ perun_rpc_hostname }}"

- name: "reload sendmail service"
  when: sendmail_reloaded.changed
  service:
    name: sendmail
    state: restarted